---

- name: Aruba AOS CX create vlans
  hosts: aruba
  gather_facts: no
  tasks:

      - name: Create VLAN 400
        arubaoss_vlan:
          vlan_id: 400
          name: "vlan400"
          config: "create"
          command: config_vlan