---

- name: Aruba AOS CX gather facts
  hosts: aoscx
  gather_facts: no
  tasks:

  - name: Aruba AOS CX get facts 
    aoscx_facts:
      gather_subset:
        #- config
    register: _facts
  
  - name: Aruba AOS CX debug facts
    debug:
      var: _facts
  